# site settings
title: Warrick Ma
email: ym464@cornell.edu
description: A personal website that describes my works and passions
# baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 290 Kimball Hall
city: Ithaca
state: NY
zip_code: 14853
country: United States of America

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/warrickma
  LinkedIn: https://www.linkedin.com/in/warrick-ma-b78a52261/
  Twitter: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
